### ISSUE TITLE
[sitemap] sitemap lastmod problem

### ISSUE THREAD

**Issue by HiDana** [junhobaik/junhobaik.github.io#57]
When I submit the sitemap in search console. I find there is a problem in the sitemap. The `lastmod` all is `2001-01-01`.

![截圖 2020-06-17 下午12 13 44](https://user-images.githubusercontent.com/20136021/84854349-ff696600-b093-11ea-85e1-80aaec7db313.png)

I find the other [issue](https://github.com/gatsbyjs/gatsby/issues/8946#issuecomment-573436217) was solved this problem.

Recommend to anyone who meets this problem.

Anyway,thanks to the author for the theme :D

**Comment by junhobaik** [comment]
@HiDana Thanks for reporting the issue :D

**Comment by HiDana** [comment]
I'm happy to help ! 😄
