### ISSUE TITLE
이미지를 포함한 게시물의 이미지 로드 문제

### ISSUE THREAD

**Issue by euneestella** [junhobaik/junhobaik.github.io#59]
마크다운으로 글을 작성하고 이미지를 첨부하면 배포했을 때 이미지가 로드되지 않습니다.

**Comment by junhobaik** [comment]
이미지가 로드되지 않는 특정 상황이 있을까요?

제 경험으로는 이미지 파일이 잘못되었을 경우 그런 경우가 있었습니다.
(예. x.jpg 파일을 x.png로 확장명을 강제로 바꿔 사용했을 경우 등)

**Comment by euneestella** [comment]
이미지는 모두 로컬에서는 잘 로드되는데, 배포하니 일부 이미지가 로드되지 않았습니다. 제 경우에는 .png 파일은 잘 로드되지만 .jpg 파일들은 로드되지 않네요.
[https://raw.githubusercontent.com/euneestella/utu_data_analysis/master/lecture_note/img/measuring-dissimilarity.PNG](url)
[https://euneestella.github.io/static/7fb52ec5916511db7233b418d82e5766/a8a14/turku-02.jpg](url)

로드되지 않는 이미지는 이미지 URL을 복사하니 /static/ 경로에 존재한다고 나왔습니다.

**Comment by junhobaik** [comment]
여러 jpg 이미지로 테스트해봤는데 아직은 전부 로드가 되고 있습니다.
혹시 로드가 안되던 이미지 파일을 보내주실 수 있나요? @euneestella

**Comment by junhobaik** [comment]
보내주신 이미지가 포함된 게시물을 @euneestella 님 레포지토리에서 복사해 그대로 제 환경에서 배포해보았는데 게시물 안의 이미지가 제대로 나왔습니다.
플러그인 모듈에서 문제가 생겼을 수 있으니 node_modules 폴더를 삭제하고 다시 npm i를 시도해보세요.

**Comment by euneestella** [comment]
조언 감사합니다. `node_modules` 폴더를 삭제한 후 패키지들의 종속성을 업데이트, `npm install` 하니 해당 문제가 수정되었습니다. 도움 주셔서 감사합니다!
