### ISSUE TITLE
excerpt 부분이 ... 으로 보이는 이슈

### ISSUE THREAD

**Issue by leshleekor** [junhobaik/junhobaik.github.io#66]
간혹가다가 excerpt 부분이 ... 으로 보이는 이슈가 있습니다.
excerpt 내용이 한국어일 때 대부분의 문서가 정상적으로 출력되지만 간혹 이런 문제가 발생하는 것 같아 정확한 원인은 모르겠습니다.

개츠비 공식 문서를 찾아보니 아래 링크와 관련된 문제같습니다.
https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

non-latin 계열 문자일때 excerpt가 정상적으로 출력되지 않는 문제인 것 같아 보입니다.
graphql excerpt부분에 `excerpt(truncate: true)` 이와 같이 truncate를 넣어주면 해결되는 것 같습니다.

**Comment by junhobaik** [comment]
해당 문제를 확인하고 수정했습니다.
@leshleekor 자세한 이슈 제보 감사합니다 👍
