### ISSUE TITLE
잔디심는거에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by fkfkfk9** [junhobaik/junhobaik.github.io#73]
깃허브로 블로그를 하려고 한 목적이 블로그도 적고 잔디도 심으려고한게 큰데
 junhobaik 님 덕분에 블로그 구현은 매우 쉽게 했습니다만 포스트를 업데이트해도 develop로 커밋을 해도 잔디가 심어지지 않습니다.
이렇게 develop에서 작성하고 master에 디폴로이를 자동으로 하는 상황에선 잔디를 심을 수 없는건가요?

**Comment by junhobaik** [comment]
github repository 설정가시면 default branch 변경하는 부분이 있습니다. 그걸 develop 브랜치로 변경하시면 develop 브랜치의 커밋 내역이 잔디로 심어집니다!

**Comment by fkfkfk9** [comment]
디폴트 브렌치를 변경했음에도 잔디가 잘 심어지지 않아서요.
당장 어제 12시 직전 책 리뷰 포스트를 하나 추가하여 디폴로이도 하고 디벨롭 커밋도 하였는데 잔디가 심어지지 않고
특히 가끔 로그인하면 보일때도 있는데 로그인하지 않으면 안보이는 상황이 있내요.
회사에서 1일1커밋하는 스터디를 하고있는데 요즘 잔디를 보여줄수가 없어서 난감합니다 ㅠㅠ

**Comment by fkfkfk9** [comment]
혹시라도 저같은 궁금증을 가진분들을 위해 답변하자면
깃허브가 fork한 레포지트리에는 잔디를 안심어주는 문제가 있더군요.
포크한 내용으로 새로운 레포지트리를 만들어주어야 잔디가 심어지내요.
